#pragma once
#include <string>

namespace ID {

	//IDÇÃëSëÃÇÇ‹Ç∆ÇﬂÇÈÅB

	enum IDType
	{
		E_MODEL,
		P_MODEL,
		S_MODEL,
		P_ANIM_IDOL,
		P_ANIM_RUN,
		P_ANIM_AVOID,
		P_ANIM_JUST_AVOID,
		P_ANIM_ATTACK1,
		P_ANIM_JUST_AVOID_ATTACK1,
		P_ANIM_ATTACK2,
		P_ANIM_JUST_AVOID_ATTACK2,
		P_ANIM_ATTACK3,
		P_ANIM_JUST_AVOID_ATTACK3,
		P_ANIM_ATTACK4,
		P_ANIM_JUST_AVOID_ATTACK4,
		P_ANIM_JUST_AVOID_ATTACK5,
		P_ANIM_ATTACK_5,
		P_DAMAGE,
		P_BLOWAWAY,
		P_FALL,
		P_GETUP,
		P_WEAPON,
		E_ANIM_IDOL,
		E_ATTACK1,
		E_DAMAGE,
		E_BLOWAWAY,
		E_FALL,
		E_GETUP,
		E_WEAPON,
		C_FOLLOW,
		C_AVOID_ATTACK,
		E_RUN,
		C_HIT,
		SKY,
		SWORD_EFFECT,
		WALL,
		PLAYER_HP_GUAGE,
		E_DIE,
		P_DIE,
		START_NUM,
		B_MODEL,
		C_FREE,
		B_IDOL,
		B_RUN,
		B_COOLTIME,
		B_ATTACKSORTING,
		B_N_ATTACK1,
		B_N_ATTACK2,
		B_N_ATTACK3,
		B_N_ATTACK4,
		B_N_ATTACK5,
		B_S_ATTACK1,
		B_S_ATTACK2,
		B_S_ATTACK3,
		B_S_ATTACK4,
		SWORD_EFFECT_B,
		BOSS_PUSH,
		BOSS_DIE,
		HP_EDGE,
		BOSS_HP_EDGE,
		TITLE_BACK,
		TITLE,
		PUSH_BUTTON,
		WIN,
		LOSE,
		B_S_ATTACK2_STOP,
		B_S_ATTACK2_BEFORE,	
		B_S_ATTACK1_SMALL,
		TE_IDOL,
		TE_RUN,
		TE_ATTACK,
		SHADOW,

		ID_MAX,
	};


	void Init();

	std::string GetID(IDType _type);
	void SetID(std::string _model, IDType _type);

}