#pragma once
#include <string>

namespace Sound_ID {

	enum SOUND_ID
	{
		SWORD_HIT_SOUND,
		SWORD_HIT_SOUND1,
		SWORD_HIT_SOUND2,
		SWORD_HIT_SOUND3,
		SWORD_HIT_SOUND4,
		SWORD_HIT_SOUND5,
		SWORD_HIT_SOUND6,
		SWORD_HIT_SOUND7,
		SWORD_HIT_SOUND8,
		SWORD_HIT_SOUND9,
		SWORD_HIT_SOUND10,
		SWORD_WIND_SOUND1,
		SWORD_WIND_SOUND2,
		SWORD_WIND_SOUND3,
		SWORD_WIND_SOUND4,
		SWORD_WIND_SOUND5,
		JUST_AVOID_SOUND,
		ENEMY_ATTACK_BEFORE,
		PLAYER_ATTACK_BEFORE,
		ENEMY_SWORD_WIND1,
		ENEMY_SWORD_WIND2,
		ENEMY_ATTACK_HIT1,
		ENEMY_ATTACK_HIT2,
		ENEMY_ATTACK_HIT3,
		ENEMY_ATTACK_HIT4,
		ENEMY_FALL,
		V_P_DAMAGE1,
		V_P_DAMAGE2,
		V_P_ATTACK1,
		V_P_ATTACK2,
		V_P_ATTACK3,
		V_P_ATTACK4,
		V_P_JUST_AVOID,
		V_P_AVOID,
		V_P_LOSE,
		V_E_DAMAGE1,
		V_E_DAMAGE2,
		V_E_DAMAGE3,
		V_E_DAMAGE4,
		V_E_ATTACK1,
		V_E_ATTACK2,
		V_E_ATTACK3,
		JUST_AVOID_SUCCESS,
		TITLE_BGM,
		PLAY_BGM,
		PUSH,
		WIN,
		LOSE,
		GROUND,
		V_B_ROAR,
		CUTIN_START,
		PLAYER_SPECIAL_ATTACK_V,
		PLAYER_SPECIAL_ATTACK_ATTACK_V1,
		PLAYER_SPECIAL_ATTACK_ATTACK_V2,
		PLAYER_SPECIAL_ATTACK_FINAL_ATTACKV,
		PLAYER_WALK1,
		PLAYER_WALK2,
		PLAYER_WALK3,
		PLAYER_WALK4,
		PLAYER_WALK5,
		BOSS_WALK,
		BOSS_ROAR_VOICE,
		BOSS_JUMP_WIND,
		BOSS_BEFORE,

		SOUND_MAX
	};

	void InitID();
	void DeleteSoundID();
	std::string GetSoundID(SOUND_ID _type);

	void SetSoundId(std::string	_sound, SOUND_ID _type);

	SOUND_ID StringToID(std::string _str);
}