#pragma once
#include <string>

namespace ID {

	//IDÇÃëSëÃÇÇ‹Ç∆ÇﬂÇÈÅB

	enum IDType
	{
		E_MODEL,
		P_MODEL,
		S_MODEL,
		P_ANIM_IDOL,
		P_ANIM_RUN,
		P_ANIM_AVOID,
		P_ANIM_JUST_AVOID,
		P_ANIM_ATTACK1,
		P_ANIM_JUST_AVOID_ATTACK1,
		P_ANIM_ATTACK2,
		P_ANIM_JUST_AVOID_ATTACK2,
		P_ANIM_ATTACK3,
		P_ANIM_JUST_AVOID_ATTACK3,
		P_ANIM_ATTACK4,
		P_ANIM_JUST_AVOID_ATTACK4,
		P_ANIM_JUST_AVOID_ATTACK5,
		P_DAMAGE,
		P_BLOWAWAY,
		P_FALL,
		P_GETUP,
		P_WEAPON,
		E_ANIM_IDOL,
		E_ATTACK1,
		E_DAMAGE,
		E_BLOWAWAY,
		E_FALL,
		E_GETUP,
		E_WEAPON,
		C_FOLLOW,
		C_AVOID_ATTACK,
		E_RUN,
		C_HIT,
		SKY,
		SWORD_EFFECT,
		WALL,
		PLAYER_HP_GUAGE,
		E_DIE,
		P_DIE,
		START_NUM,

		ID_MAX,
	};

	enum EFFECT_ID
	{
		ENEMY_FLASH,
		HIT_EFFECT,
		SPECIAL_HIT_EFFECT,
		JUST_AVOID_EFFECT,
		PLAYER_FLASH,
		PLAYER_AURA,
		PLAYER_HIT,
		PLAYER_ATTACK,
		PLAYER_SLASH_ATTACK,
		ENEMY_ATTACK_CICLE,
		EFFECT_WALL,
		EFFECT_MAX
	};

	enum SOUND_ID
	{
		SWORD_HIT_SOUND,
		SWORD_HIT_SOUND1,
		SWORD_HIT_SOUND2,
		SWORD_HIT_SOUND3,
		SWORD_HIT_SOUND4,
		SWORD_HIT_SOUND5,
		SWORD_HIT_SOUND6,
		SWORD_HIT_SOUND7,
		SWORD_HIT_SOUND8,
		SWORD_HIT_SOUND9,
		SWORD_HIT_SOUND10,
		SWORD_WIND_SOUND1,
		SWORD_WIND_SOUND2,
		SWORD_WIND_SOUND3,
		SWORD_WIND_SOUND4,
		SWORD_WIND_SOUND5,
		JUST_AVOID_SOUND,
		ENEMY_ATTACK_BEFORE,
		PLAYER_ATTACK_BEFORE,
		ENEMY_SWORD_WIND1,
		ENEMY_SWORD_WIND2,
		ENEMY_ATTACK_HIT1,
		ENEMY_ATTACK_HIT2,
		ENEMY_ATTACK_HIT3,
		ENEMY_ATTACK_HIT4,
		ENEMY_FALL,
		V_P_DAMAGE1,
		V_P_DAMAGE2,
		V_P_ATTACK1,
		V_P_ATTACK2,
		V_P_ATTACK3,
		V_P_ATTACK4,
		V_P_JUST_AVOID,
		V_P_AVOID,
		V_P_LOSE,
		V_E_DAMAGE1,
		V_E_DAMAGE2,
		V_E_DAMAGE3,
		V_E_DAMAGE4,
		V_E_ATTACK1,
		V_E_ATTACK2,
		V_E_ATTACK3,
		JUST_AVOID_SUCCESS,

		SOUND_MAX
	};

	void Init();

	std::string GetID(IDType _type);

	std::string GetSoundID(SOUND_ID _type);

	void SetSoundId(std::string	_sound, SOUND_ID _type);

	std::string GetEffectID(EFFECT_ID _type);

	void SetEffectID(std::string _effect, EFFECT_ID _type);
}